name: CI/CD DevOps Final

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Instalar dependencias y ejecutar pruebas
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar pruebas unitarias
        run: npm test

  docker:
    name: Crear y subir imagen Docker
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir imagen Docker
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devops-final:latest .

      - name: Subir imagen a Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-final:latest